[project]
name = "world-economic-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dagster>=1.13.23",
    "dagster-dbt>=0.29.23",
    "dagster-postgres>=0.29.23",
    "dagster-project",
    "dagster-webserver>=1.13.23",
    "dbt-clickhouse>=1.10.3",
    "dbt-postgres>=1.11.0",
    "pandas>=3.0.5",
    "requests>=2.34.2",
]

[tool.uv.workspace]
members = [
    "dagster_project",
]

[tool.uv.sources]
dagster-project = { workspace = true, editable = true }
